- blossom-ui/blossom-ui-web/src/main/resources/templates/utils/table.ftl
Make the table in table.ftl responsive
> Table responsive

- blossom-autoconfigure/src/main/java/fr/mgargadennec/blossom/autoconfigure/ui/web/module/WebFileManagerAutoConfiguration.java
- blossom-core/blossom-core-group/src/main/java/fr/mgargadennec/blossom/core/group/GroupCreateForm.java
- blossom-core/blossom-core-group/src/main/java/fr/mgargadennec/blossom/core/group/GroupService.java
- blossom-core/blossom-core-group/src/main/java/fr/mgargadennec/blossom/core/group/GroupServiceImpl.java
- blossom-core/blossom-core-group/src/main/java/fr/mgargadennec/blossom/core/group/GroupUpdateForm.java
- blossom-core/blossom-core-group/src/main/resources/messages/groups.properties
- blossom-core/blossom-core-group/src/main/resources/messages/groups_en.properties
- blossom-core/blossom-core-group/src/main/resources/messages/groups_fr.properties
- blossom-core/blossom-core-role/src/main/java/fr/mgargadennec/blossom/core/role/RoleCreateForm.java
- blossom-core/blossom-core-role/src/main/java/fr/mgargadennec/blossom/core/role/RoleService.java
- blossom-core/blossom-core-role/src/main/java/fr/mgargadennec/blossom/core/role/RoleServiceImpl.java
- blossom-core/blossom-core-role/src/main/java/fr/mgargadennec/blossom/core/role/RoleUpdateForm.java
- blossom-core/blossom-core-role/src/main/resources/messages/roles.properties
- blossom-core/blossom-core-role/src/main/resources/messages/roles_en.properties
- blossom-core/blossom-core-role/src/main/resources/messages/roles_fr.properties
- blossom-ui/blossom-ui-web/src/main/java/fr/mgargadennec/blossom/ui/web/administration/group/GroupsController.java
- blossom-ui/blossom-ui-web/src/main/java/fr/mgargadennec/blossom/ui/web/administration/role/RolesController.java
- blossom-ui/blossom-ui-web/src/main/resources/templates/groups/create.ftl
- blossom-ui/blossom-ui-web/src/main/resources/templates/groups/group.ftl
- blossom-ui/blossom-ui-web/src/main/resources/templates/groups/groups.ftl
- blossom-ui/blossom-ui-web/src/main/resources/templates/groups/update.ftl
- blossom-ui/blossom-ui-web/src/main/resources/templates/roles/create.ftl
- blossom-ui/blossom-ui-web/src/main/resources/templates/roles/role.ftl
- blossom-ui/blossom-ui-web/src/main/resources/templates/roles/roles.ftl
- blossom-ui/blossom-ui-web/src/main/resources/templates/roles/update.ftl
Cle sous le namespace:
blossom.filemanager.enabled
Impossible de lire un fichier de properties lors de la configuration,
donc si clé non présente, true par défaut.
> Possibilite de disable un module

- blossom-modules/blossom-module-filemanager/src/main/java/fr/mgargadennec/blossom/module/filemanager/FileContentDaoImpl.java
- blossom-samples/blossom-sample-filemanager/src/main/resources/db/changelog/db.changelog-master.yaml
- blossom-samples/blossom-sample-scheduler/src/main/resources/db/changelog/db.changelog-master.yaml
- blossom-samples/blossom-samples-basic/src/main/resources/db/changelog/db.changelog-master.yaml
- blossom-samples/blossom-samples-ui/src/main/resources/db/changelog/db.changelog-master.yaml
Couple of fixes to make all samples run:
- Added DB changelog to avoid failing at fr/mgargadennec/blossom/autoconfigure/core/LiquibaseAutoConfiguration.java:47
- Changed fr.mgargadennec.blossom.module.filemanager.FileContentDaoImpl because it was referencing "QFileContent" which doesn't exist anymore (?).
> Fix samples

- blossom-core/blossom-core-common/src/main/java/fr/blossom/core/common/utils/mail/MailSenderImpl.java
- blossom-core/blossom-core-common/src/main/java/fr/blossom/core/common/utils/mail/NoopMailSenderImpl.java
- blossom-core/blossom-core-user/src/main/resources/templates/mail/user-activation.ftl
- blossom-core/blossom-core-user/src/main/resources/templates/mail/user-change-password.ftl
Couple changes to mails:
- Changed logger wording because args didn't match the template
- Fixed arguments in user-related mail templates
> Activation mail

- docs/index.md
Add an example of command line runner to always trigger a Quartz job on application start
> Add run job on application start doc & minor doc changes

- blossom-core/blossom-core-common/src/main/java/fr/blossom/core/common/utils/liquibase/BlossomSpringLiquibase.java
- blossom-tools/blossom-tools-initializr/src/main/resources/changelog/db.changelog-master.yaml
- blossom-tools/blossom-tools-simple-module-generator/src/main/java/fr/blossom/generator/resources/ChangelogGenerator.java
- Fix classpath*: paths for paths other than `db/changelog/blossom`
- Module generator creates changelogs into db/changelog/blossom/modules
- Add `classpath*:db/changelog/blossom/modules` into default (initializr) changelog includes
> Liquibase changelogs

- blossom-tools/blossom-tools-simple-module-generator/src/main/java/com/blossomproject/generator/GeneratorExample.java
- blossom-tools/blossom-tools-simple-module-generator/src/main/java/com/blossomproject/generator/classes/ConfigurationGenerator.java
- blossom-tools/blossom-tools-simple-module-generator/src/main/java/com/blossomproject/generator/classes/DtoGenerator.java
- blossom-tools/blossom-tools-simple-module-generator/src/main/java/com/blossomproject/generator/classes/EntityGenerator.java
- blossom-tools/blossom-tools-simple-module-generator/src/main/java/com/blossomproject/generator/classes/IndexationJobGenerator.java
- blossom-tools/blossom-tools-simple-module-generator/src/main/java/com/blossomproject/generator/configuration/EnumFieldBuilder.java
- blossom-tools/blossom-tools-simple-module-generator/src/main/java/com/blossomproject/generator/configuration/ExecutionPlanBuilder.java
- blossom-tools/blossom-tools-simple-module-generator/src/main/java/com/blossomproject/generator/configuration/FieldsBuilder.java
- blossom-tools/blossom-tools-simple-module-generator/src/main/java/com/blossomproject/generator/configuration/model/impl/EnumField.java
- blossom-tools/blossom-tools-simple-module-generator/src/main/java/com/blossomproject/generator/resources/ChangelogGenerator.java
- blossom-tools/blossom-tools-simple-module-generator/src/main/java/com/blossomproject/generator/resources/ElasticSearchSourceGenerator.java
- blossom-tools/blossom-tools-simple-module-generator/src/main/java/com/blossomproject/generator/utils/GeneratorUtils.java
- blossom-tools/blossom-tools-simple-module-generator/src/main/resources/create.ftl
- blossom-tools/blossom-tools-simple-module-generator/src/main/resources/entityinformations-edit.ftl
- blossom-tools/blossom-tools-simple-module-generator/src/main/resources/entityinformations.ftl
- blossom-ui/blossom-ui-web/src/main/resources/templates/blossom/utils/buttons.ftl
Generator can handle Enum type and render it as select input in Back-office forms.
I've also added the generation of Elasticsearch settings, mapping (json) and IndexationJob and Trigger.
The search functionality of the backoffice is now working.
> Generator : Enum Type + Indexation Elasticsearch

- blossom-tools/blossom-tools-simple-module-generator/src/main/java/com/blossomproject/generator/utils/GeneratorUtils.java
- blossom-tools/blossom-tools-simple-module-generator/src/main/resources/create.ftl
- blossom-tools/blossom-tools-simple-module-generator/src/main/resources/entityinformations-edit.ftl
- blossom-tools/blossom-tools-simple-module-generator/src/main/resources/entityinformations.ftl
> Generator : Textarea input for @Lob String

- blossom-ui/blossom-ui-web/src/main/resources/templates/blossom/home/home.ftl
Separation of the different menuItem to improve the visibility.
> Back-office homepage with panel for each menuItem.

- blossom-tools/blossom-tools-simple-module-generator/src/main/java/com/blossomproject/generator/classes/ApiControllerGenerator.java
- blossom-tools/blossom-tools-simple-module-generator/src/main/java/com/blossomproject/generator/configuration/ExecutionPlanBuilder.java
- blossom-tools/blossom-tools-simple-module-generator/src/main/java/com/blossomproject/generator/utils/GeneratorUtils.java
Generate basic API operations of the entity in EntityApiController:
-page
-get (id)
-create(id)
-update (id)
-delete(id)
> Generator : ApiController generation

- blossom-ui/blossom-ui-web/src/main/java/com/blossomproject/ui/web/ActivationController.java
Just a rewriting of the condition to be sure that we set resetPasswordMail to true only if we actually call askPasswordChange()
I used Optional.orElse() to avoid using multiple if and else conditions.
> Fix in askForForgottenPassword POST Controller.

- blossom-ui/blossom-ui-api/src/main/java/com/blossomproject/ui/api/StatusApiController.java
- blossom-ui/blossom-ui-api/src/test/java/com/blossomproject/ui/api/OmnisearchApiControllerTest.java
- blossom-ui/blossom-ui-api/src/test/java/com/blossomproject/ui/api/StatusApiControllerTest.java
- blossom-ui/blossom-ui-common/src/test/java/com/blossomproject/ui/LastConnectionUpdateAuthenticationSuccessHandlerImplTest.java
- blossom-ui/blossom-ui-web/pom.xml
- blossom-ui/blossom-ui-web/src/test/java/com/blossomproject/ui/web/OmnisearchControllerTest.java
- blossom-ui/blossom-ui-web/src/test/java/com/blossomproject/ui/web/StatusControllerTest.java
- blossom-ui/blossom-ui-web/src/test/java/com/blossomproject/ui/web/content/filemanager/FileManagerControllerTest.java
- blossom-ui/blossom-ui-web/src/test/java/com/blossomproject/ui/web/system/scheduler/SchedulerControllerTest.java
- blossom-ui/blossom-ui-web/src/test/java/com/blossomproject/ui/web/system/sessions/SessionControllerTest.java
- SessionControllerTest
- SchedulerControllerTest
- FileManagerControllerTest
- StatusApiControllerTest
- OmnisearchApiControllerTest
- LastConnectionUpdateAuthenticationSuccessHandlerImplTest
> Unit Testing

- blossom-ui/blossom-ui-web/src/main/resources/templates/blossom/profile/profile.ftl
> Fix profile page for users with empty values

- blossom-ui/blossom-ui-web/src/main/java/com/blossomproject/ui/web/system/cache/CacheManagerController.java
as title says.
By the way, the "cache" map on controller can be created without having to update it post-création.
I find this way of creating it more elegant than creating it then updating it in a loop.
> make cache search case insensitive

- blossom-core/blossom-core-user/src/main/java/com/blossomproject/core/user/User.java
- blossom-core/blossom-core-user/src/main/resources/db/changelog/blossom/0_db.changelog-blossom_core_user.xml
Fix #162 
Note that the "function" column is not deleted at this point, we probably should not delete until at least the next version.
> Rename "function" column to "job_title"

- blossom-autoconfigure/src/main/java/com/blossomproject/autoconfigure/ui/WebSecurityAutoConfiguration.java
- blossom-autoconfigure/src/main/java/com/blossomproject/autoconfigure/ui/web/BlossomWebBackOfficeProperties.java
- blossom-autoconfigure/src/main/java/com/blossomproject/autoconfigure/ui/web/WebInterfaceAutoConfiguration.java
- blossom-autoconfigure/src/main/resources/security.properties
- blossom-ui/blossom-ui-common/src/main/java/com/blossomproject/ui/BlossomAuthenticationSuccessHandlerImpl.java
- blossom-ui/blossom-ui-common/src/test/java/com/blossomproject/ui/BlossomAuthenticationSuccessHandlerImplTest.java
> Add ability to configure session length and max session per user

- blossom-core/blossom-core-user/src/main/resources/messages/activation_fr.properties
> traduction en français du mail

- blossom-ui/blossom-ui-web/src/main/java/com/blossomproject/ui/web/system/logger/LoggerManagerController.java
> Authority loggers

- blossom-ui/blossom-ui-web/src/main/resources/templates/blossom/utils/tabulation.ftl
#172 fixed !
Loader is stopped and an error message is displayed.
> Bug fix : Bad handling errors with tabs

- blossom-core/blossom-core-cache/src/main/resources/messages/caches.properties
- blossom-core/blossom-core-cache/src/main/resources/messages/caches_fr.properties
- blossom-ui/blossom-ui-web/src/main/java/com/blossomproject/ui/web/system/cache/CacheManagerController.java
- blossom-ui/blossom-ui-web/src/main/resources/templates/blossom/system/caches/caches.ftl
> Add empty all caches button #226
