blossom-project/blossom

blossom-core/blossom-core-user/src/main/resources/templates/mail/user-change-password.ftl
When requesting a password reset, the link sent contains a "USER_RESET_PASSWORD" action token, but points to the /activate endpoint, which only accepts "USER_ACTIVATION" action token.
This fixes the url to point directly to /change_password, since we may not want to allow users to activate their account with a reset password link. If we do, we should instead change the action token type to "USER_ACTIVATION" in fr/blossom/core/user/UserMailServiceImpl.java:46
=> Fix reset password sending to activation link instead of change_password link

blossom-core/blossom-core-scheduler/src/main/java/fr/blossom/core/scheduler/history/TriggerHistoryDaoImpl.java
Job/Trigger Group/Name were swapped when getting information back from the DB.
Also, for Lists.newArrayList(): its Javadoc contains `Note for Java 7 and later: this method is now unnecessary and should be treated as deprecated` so I replaced it.
Would it be worth it to create an entity/jpa repository here?
=> Fix TriggerHistory loading from DB

blossom-ui/blossom-ui-web/src/main/java/fr/blossom/ui/web/ActivationController.java, blossom-ui/blossom-ui-web/src/main/resources/templates/activation/change-password.ftl
When submitting the password reset form, we're still on the /reset_password?token=<token here> page.
Submitting the form causes the browser to submit the token twice:
- First as a query param
- Also as a hidden form param
Which means that instead of the token, fr/blossom/ui/web/ActivationController.java:96 tries to validate a string made of the token twice separated by a comma, and fails.
This fix removes the extra token added in the form, and assumes that we got on the page with the token as a query string.
=> Remove double reset password token submit

blossom-autoconfigure/src/main/java/fr/blossom/autoconfigure/core/UserAutoConfiguration.java, blossom-core/blossom-core-common/src/main/java/fr/blossom/core/common/utils/action_token/ActionToken.java, blossom-core/blossom-core-common/src/main/java/fr/blossom/core/common/utils/action_token/ActionTokenServiceImpl.java, blossom-core/blossom-core-common/src/test/java/fr/blossom/core/common/utils/action_token/ActionTokenServiceImplTest.java, blossom-core/blossom-core-user/src/main/java/fr/blossom/core/user/UserMailService.java, blossom-core/blossom-core-user/src/main/java/fr/blossom/core/user/UserMailServiceImpl.java, blossom-core/blossom-core-user/src/main/java/fr/blossom/core/user/UserService.java, blossom-core/blossom-core-user/src/main/java/fr/blossom/core/user/UserServiceImpl.java, blossom-core/blossom-core-user/src/test/java/fr/blossom/core/user/UserMailServiceImplTest.java, blossom-core/blossom-core-user/src/test/java/fr/blossom/core/user/UserServiceImplTest.java, blossom-ui/blossom-ui-web/src/main/java/fr/blossom/ui/web/ActivationController.java
- Changed the "expiration date" to an Instant in ActionToken, so that timezone difference can not cause trouble (for example for applications with multiple instances that may have different default timezones, but shared stateless tokens).
- Added token invalidation once a user logs in for tokens allowing it to activate its account, or reset its password. Assumption is that once the user manages to log in, it didn't need that token anymore.
To this end, activation/password reset tokens are now generated from the UserServiceImpl and nowhere else, so we are free to put any additional needed parameters in the token. Right now the creation time is added.
=> Action token dates & activation/password reset tokens invalidation

pom.xml
Add maven-source-plugin and maven-javadoc-plugin to have the sources and doc generated and published at the same time as the rest of the project.
=> Add source & javadoc jars when packaging

blossom-tools/blossom-tools-initializr/pom.xml, blossom-tools/blossom-tools-initializr/src/main/java/fr/blossom/initializr/InitializrController.java, blossom-tools/blossom-tools-initializr/src/main/java/fr/blossom/initializr/ProjectConfiguration.java, blossom-tools/blossom-tools-initializr/src/main/java/fr/blossom/initializr/ProjectGenerator.java, blossom-tools/blossom-tools-initializr/src/main/java/fr/blossom/initializr/Version.java, blossom-tools/blossom-tools-initializr/src/main/java/fr/blossom/initializr/enums/PACKAGING_MODE.java, blossom-tools/blossom-tools-initializr/src/main/java/fr/blossom/initializr/enums/SOURCE_LANGUAGE.java, blossom-tools/blossom-tools-initializr/src/main/resources/application.yml, blossom-tools/blossom-tools-initializr/src/main/resources/templates/main.ftl
Add a "source language" option for the project initializr, with the following options:
- Java (default)
- Mixed Java + Kotlin
- Kotlin only
The configurations are taken from [kotlin doc](https://kotlinlang.org/docs/reference/using-maven.html) : Java + Kotlin allows to have sources in both java (src/main/java) and kotlin (src/main/kotlin) in the same project. Kotlin-only replaces java and the only source directory becomes src/main/kotlin.
Kotlin source generation uses [kotlinpoet](https://github.com/square/kotlinpoet) and could be improved a bit...
=> Add kotlin source language for project initializr

blossom-autoconfigure/pom.xml
Adding the spring-boot-configuration-processor to classpath, even as optional, creates spring-configuration-metadata.json in the correct path.
This provides IDE with auto-completion for blossom-related configuration.
=> Add spring-boot-configuration-processor to autoconfigure

blossom-core/blossom-core-scheduler/pom.xml
Exclude HikariCP-java6:2.3.13 from spring-boot-starter-quartz for cases when it would get loaded before HikariCP:2.7.8, causing the application to fail starting at all : spring-boot-starter-actuator relies on methods not present in version 2.3.13.
=> HikariCP-java6 exclusion

blossom-autoconfigure/src/main/java/com/blossomproject/autoconfigure/core/MailAutoConfiguration.java, blossom-autoconfigure/src/main/resources/mailsender.properties
With the previous configuration, I was unable to have more than one mail filter, no matter what I tried to put in my configurations to override the default.
After this change, the following syntaxes all work to override the filter:
---
application.properties
```properties
blossom.mail.filters=test@cardiweb.com
```
Result: one filter, `test@cardiweb.com`
---
application.properties
```properties
blossom.mail.filters=test@cardiweb.com,test2@cardiweb.com
```
Result: two filters, `test@cardiweb.com` and `test2@cardiweb.com`
---
application.properties
```properties
blossom.mail.filters[0]=test@cardiweb.com
blossom.mail.filters[1]=test2@cardiweb.com
```
Result: two filters, `test@cardiweb.com` and `test2@cardiweb.com`
---
application.yml
```yaml
blossom.mail.filters: "test@cardiweb.com"
``` …
=> Fix mail filters

blossom-ui/blossom-ui-web/src/main/java/com/blossomproject/ui/web/StatusController.java, blossom-ui/blossom-ui-web/src/test/java/com/blossomproject/ui/web/StatusControllerTest.java
- Changed the filtered health status to use an `OrderedHealthAggregator` to accurately represent the filtered result
- Added ability to selectively include healths with names allowing nested selections.
For example, if `curl http://localhost:8080/blossom/public/status` answers:
```json
{
"status": "DOWN",
"details": {
"upSubRoot": {
"status": "UP",
"details": {
"healthLeafUp": {
"status": "UP"
},
"healthLeafStillUp": {
"status": "UP"
}
}
},
"level2SubRoot": {
"status": "DOWN",
"details": {
"upSubRoot": {
"status": "UP",
"details": {
"healthLeafUp": {
"status": "UP"
},
"healthLeafStillUp": {
"status": "UP"
}
}
},
"downSubRoot": {
"status": "DOWN",
"details": {
"healthLeafDown": {
"status": "DOWN"
},
"healthLeafUp": {
"status": "UP"
}
}
}
}
}
}
}
```
Then `curl …
=> Supervision status page improvements

blossom-tools/blossom-tools-simple-module-generator/src/main/java/com/blossomproject/generator/configuration/LongFieldBuilder.java
change the jdbc type to "bigint" in the LongFieldBuilder
=> LongFieldBuilder JDBC type "long" badly translate to mediumtext on MySQL

blossom-ui/blossom-ui-web/src/main/resources/templates/blossom/utils/pagination.ftl
Actually, the pager display "page 1-0 of 0" if there is nothing to display.  
This simply remove the pagination if there is no result.
=> If there is no page, remove pagiation instead of displaying 1-0 of 0

blossom-ui/blossom-ui-web/src/main/resources/templates/blossom/utils/table.ftl
When you apply a search with an empty date filter you had a "default error page" because **startDate** and **endDate** were not initialized.
=> fix date filter initialization

.gitignore, CHANGELOG.md, changelog.mustache, pom.xml
Add a maven plugin to allow automated changelog generation with `mvn git-changelog-maven-plugin:git-changelog`
I'm still not a fan of putting every commit that did not go through an issue / a pull request "as is" in the changelog. Should we use the plugin to generate a first version of the changelog then manually update it? Or start making sure everything goes through a PR ?
=> Automated changelog

blossom-ui/blossom-ui-web/src/main/resources/templates/blossom/system/liquibase/liquibase.ftl
I suppose it's more interresting to see last db changes first.
=> Display db migration in reverse order so last changes appears first

blossom-core/blossom-core-scheduler/src/main/java/com/blossomproject/core/scheduler/history/TriggerHistoryDaoImpl.java, blossom-core/blossom-core-scheduler/src/main/java/com/blossomproject/core/scheduler/listener/GlobalTriggerListener.java, blossom-core/blossom-core-scheduler/src/test/java/com/blossomproject/core/scheduler/listener/GlobalTriggerListenerTest.java
Fix #181  
Any exception thrown during Quartz's listener trigger breaks the job for which the listener was called.
In the issue's example, the exception was `org.springframework.transaction.CannotCreateTransactionException`, caused by having `@Transactional` on the listener's method directly. I have moved the transactional part to the DAO directly, and wrapped the DAO call in a try/catch intercepting any exception to prevent the scheduler from breaking.
=> Do not throw any exception in GlobalTriggerListener

blossom-autoconfigure/src/main/java/com/blossomproject/autoconfigure/ui/DefaultAccountProperties.java, blossom-autoconfigure/src/main/java/com/blossomproject/autoconfigure/ui/WebSecurityAutoConfiguration.java, blossom-autoconfigure/src/main/resources/security.properties, blossom-core/blossom-core-association-user-role/src/main/java/com/blossomproject/core/association_user_role/AssociationUserRoleDao.java, blossom-core/blossom-core-association-user-role/src/main/java/com/blossomproject/core/association_user_role/AssociationUserRoleDaoImpl.java, blossom-core/blossom-core-association-user-role/src/test/java/com/blossomproject/core/association_user_role/AssociationUserRoleDaoImplIntegrationTest.java, blossom-core/blossom-core-association-user-role/src/test/java/com/blossomproject/core/association_user_role/DaoTestContext.java
Fix #179 
- "system" account password is randomized and shown in logs at application startup when it is activated
- Default is not to always activate the "system" account. Instead, it is only activated if there are no actual account created with enough privileges to grant more privileges, that could be used to recover back-office access (at least by granting itself more privileges if needed).
Note that it is possible to override the password and system account activation to recover previous workflow, but it must now be a conscious decision.
Also note that looking for a user with enough privileges to decide if the system account should be enabled will slow down startup somewhat, it is still recommended to explicitly disable system account when not needed.
=> Better security default for system account

blossom-core/blossom-core-scheduler/src/main/resources/db/changelog/blossom/0_db.changelog-blossom_core_scheduler_trigger_history.xml
Fix #185 
MariaDB 10.1 using debian/ubuntu packages uses utf8mb4 by default, but keeps the 767 bytes limit for indexes.
Other installation methods (using mariadb-provided packages, or docker) still use latin1 by default, which does not encounter the problem. MariaDB 10.2 and up have a higher limit, and do not fail even with utf8 encoding. MySQL does not encounter the problem since its default is still latin1 until mysql 8.0, which accepts longer keys.
This "fix" forces latin1 encoding for MariaDB 10.1 only, on the "job_name" and "job_group" columns, so the key size remains small enough.
=> Force latin1 encoding for job names and groups in trigger history

blossom-tools/blossom-tools-simple-module-generator/src/main/java/com/blossomproject/generator/configuration/BlobFieldBuilder.java, blossom-tools/blossom-tools-simple-module-generator/src/main/java/com/blossomproject/generator/configuration/EnumFieldBuilder.java, blossom-tools/blossom-tools-simple-module-generator/src/main/java/com/blossomproject/generator/configuration/model/impl/EnumField.java, blossom-tools/blossom-tools-simple-module-generator/src/main/java/com/blossomproject/generator/utils/GeneratorUtils.java
Fix #165 and #167 :
- Use the longest enum name for varchar column size
- Use "longblob" as liquibase type for blobs, validates fine on H2 and MySQL databases
- Do not show "blob" fields in the generated entity view
=> Module generator mysql

blossom-core/blossom-core-common/src/main/java/com/blossomproject/core/common/utils/mail/MailFilterImpl.java, blossom-core/blossom-core-common/src/test/java/com/blossomproject/core/common/utils/mail/MailFilterImplTest.java
Since the switch to using InternetAddresses for emails, previous filter regexes would not work for the same emails (due to not having `>` at the end most of the time).
The filter now only applies to the actual address part, and ignores the personal + formatting of InternetAddress.
=> Fix filter for InternetAddress with personnal

blossom-tools/blossom-tools-simple-module-generator/src/main/java/com/blossomproject/generator/classes/ServiceImplGenerator.java
Remove duplicate UpdatedEvent<AbstractDTO> event fired in generated `DTO update(Long id, EntityUpdateForm form)` method: since we're calling `com.blossomproject.core.common.service.GenericCrudServiceImpl#update(long, DTO)` anyway.
@mgargadennec : I am also not sure about the `isRequiredCreate` for the create method: are we not supposed to add "non-required" fields manually if they are present in the creation form?
=> Generation improvements

blossom-core/blossom-core-common/src/main/java/com/blossomproject/core/common/utils/mail/MailSenderImpl.java, blossom-core/blossom-core-common/src/main/java/com/blossomproject/core/common/utils/mail/NoopMailSenderImpl.java
Change log level to warn when javamail is incorrectly or not configured
=> close #180 : Unconfigured mail use warn logger instead of info

blossom-core/blossom-core-common/src/main/java/com/blossomproject/core/common/utils/mail/NoopMailSenderImpl.java
Remove `LOGGER.isInfoEnabled()` for warn level log
=> Fix mail loglevel for NoopMailSenderImpl

blossom-core/blossom-core-common/src/main/java/com/blossomproject/core/common/utils/mail/MailFilterImpl.java, blossom-core/blossom-core-common/src/main/java/com/blossomproject/core/common/utils/mail/MailSenderImpl.java, blossom-core/blossom-core-common/src/main/java/com/blossomproject/core/common/utils/mail/NoopMailSenderImpl.java, blossom-core/blossom-core-common/src/test/java/com/blossomproject/core/common/utils/mail/MailSenderImplTest.java, blossom-core/blossom-core-common/src/test/resources/templates/mail/htmlTemplate.ftl
A couple MailSender fixes:
- Allow sending mails with BCC-only recipients, so no one can see who received the message
- Fix methods sending to multiple recipients (of any type) using String[] instead of InternetAddress[]
Fixes #194
=> MailSender allow BCC-only and multiple recipients

blossom-autoconfigure/src/main/java/com/blossomproject/autoconfigure/core/CommonAutoConfiguration.java, blossom-core/blossom-core-common/pom.xml, blossom-core/blossom-core-validation/pom.xml, blossom-modules/blossom-module-bpmn/pom.xml, blossom-parent/pom.xml, pom.xml
The goal of this PR is to allow full Java11 compatibility:
- Projects running with Java11 with no warnings
- Projects building targeting release 11
- Blossom build with Java11, including release targeting to 11 (even if this isn't the case for now)
Changes to this effect:
- Upgrade to Spring Boot 2.1
- Add dependencies to Java modules that are no longer part of the JDK: javax.annotation, jaxb-runtime
- Upgrade maven plugins to versions that support Java 11: Jacoco 0.8.2, maven-javadoc-plugin 3.0.1
- Security upgrade : apache tika to 1.20
- Camunda starter from 2.2.0 to 3.2.0 to work with Spring Boot 2.1
- Removed implicit bean overriding for `MessageSource` since bean overriding is disabled by default with Spring Boot 2.1, instead extending the default MessageSource
Question:
=> Java 11 compatibility & Spring boot 2.1

blossom-autoconfigure/src/main/java/com/blossomproject/autoconfigure/core/MailAutoConfiguration.java, blossom-core/blossom-core-common/src/main/java/com/blossomproject/core/common/utils/mail/AsyncMailSender.java, blossom-core/blossom-core-common/src/main/java/com/blossomproject/core/common/utils/mail/AsyncMailSenderImpl.java, blossom-core/blossom-core-common/src/main/java/com/blossomproject/core/common/utils/mail/BlossomMail.java, blossom-core/blossom-core-common/src/main/java/com/blossomproject/core/common/utils/mail/BlossomMailAttachment.java, blossom-core/blossom-core-common/src/main/java/com/blossomproject/core/common/utils/mail/BlossomMailBuilder.java, blossom-core/blossom-core-common/src/main/java/com/blossomproject/core/common/utils/mail/BlossomMailBuilderImpl.java, blossom-core/blossom-core-common/src/main/java/com/blossomproject/core/common/utils/mail/BlossomMailImpl.java, blossom-core/blossom-core-common/src/main/java/com/blossomproject/core/common/utils/mail/DeprecatedMailSender.java, blossom-core/blossom-core-common/src/main/java/com/blossomproject/core/common/utils/mail/DeprecatedMailSenderImpl.java, blossom-core/blossom-core-common/src/main/java/com/blossomproject/core/common/utils/mail/FileMailAttachment.java, blossom-core/blossom-core-common/src/main/java/com/blossomproject/core/common/utils/mail/InputStreamMailAttachment.java, blossom-core/blossom-core-common/src/main/java/com/blossomproject/core/common/utils/mail/MailFilter.java, blossom-core/blossom-core-common/src/main/java/com/blossomproject/core/common/utils/mail/MailFilterImpl.java, blossom-core/blossom-core-common/src/main/java/com/blossomproject/core/common/utils/mail/MailSender.java, blossom-core/blossom-core-common/src/main/java/com/blossomproject/core/common/utils/mail/MailSenderImpl.java, blossom-core/blossom-core-common/src/main/java/com/blossomproject/core/common/utils/mail/NoopMailSenderImpl.java, blossom-core/blossom-core-common/src/test/java/com/blossomproject/core/common/utils/mail/DeprecatedMailSenderImplTest.java, blossom-core/blossom-core-common/src/test/java/com/blossomproject/core/common/utils/mail/MailFilterImplTest.java, blossom-core/blossom-core-common/src/test/java/com/blossomproject/core/common/utils/mail/MailSenderImplTest.java, blossom-core/blossom-core-common/src/test/resources/templates/mail/textTemplate.ftl, blossom-core/blossom-core-common/src/test/resources/templates/mail/textTemplateWithContext.ftl, blossom-core/blossom-core-common/src/test/resources/templates/mail/textTemplateWithTranslation.ftl, blossom-core/blossom-core-user/src/main/java/com/blossomproject/core/user/UserMailServiceImpl.java, blossom-core/blossom-core-user/src/test/java/com/blossomproject/core/user/UserMailServiceImplTest.java
Rework MailSender's interface.
The goals of this new interface avoid doubling the number of methods for each new functionality, like what happened with addresses going from `String` to `InternetAddress` ; as well as being easier to work with by only using the methods you need.
How it works:
- MailSender is now a simple interface with only one method: create BlossomMailBuilder
- BlossomMailBuilder is an interface for mail parameters, including subject, body, sender, recipients, filters, attachments...
- BlossomMail is an interface once a mail has been built, to send it off synchronously or asynchronously
- BlossomMail's default implementation stores parameters, and passes them back to the MailSender's default implementation
Note on async: since the "send" method is now not part of the …
=> Mailsender interface

blossom-autoconfigure/src/main/java/com/blossomproject/autoconfigure/core/SchedulerAutoConfiguration.java, blossom-autoconfigure/src/main/resources/scheduler.properties, blossom-core/blossom-core-scheduler/src/main/java/com/blossomproject/core/scheduler/history/TriggerHistory.java, blossom-core/blossom-core-scheduler/src/main/java/com/blossomproject/core/scheduler/history/TriggerHistoryCleanJob.java, blossom-core/blossom-core-scheduler/src/main/java/com/blossomproject/core/scheduler/history/TriggerHistoryDaoImpl.java, blossom-core/blossom-core-scheduler/src/main/java/com/blossomproject/core/scheduler/history/TriggerHistoryRepository.java, blossom-core/blossom-core-scheduler/src/main/java/com/blossomproject/core/scheduler/listener/GlobalTriggerListener.java, blossom-core/blossom-core-scheduler/src/test/java/com/blossomproject/core/scheduler/listener/GlobalTriggerListenerTest.java
- Delegate TriggerHistory DB access to a JPARepository
- When getting JobInfo, actually load only the first "max-history-size" triggers
- Periodically delete all trigger history older than "max-history-age" (default 15 days)
=> Trigger history

blossom-core/blossom-core-cache/src/main/java/com/blossomproject/core/cache/BlossomCache.java, blossom-core/blossom-core-cache/src/test/java/com/blossomproject/core/cache/BlossomCacheTest.java
=> Do not wrap results for cache storage when bypassing cache altogether

blossom-autoconfigure/src/main/java/com/blossomproject/autoconfigure/core/ActuatorAutoConfiguration.java, blossom-autoconfigure/src/main/java/com/blossomproject/autoconfigure/core/CommonAutoConfiguration.java, blossom-autoconfigure/src/main/java/com/blossomproject/autoconfigure/core/ElasticsearchAutoConfiguration.java, blossom-autoconfigure/src/main/java/com/blossomproject/autoconfigure/ui/MenuAutoConfiguration.java, blossom-autoconfigure/src/main/java/com/blossomproject/autoconfigure/ui/ThemeAutoConfiguration.java, blossom-autoconfigure/src/main/java/com/blossomproject/autoconfigure/ui/WebContextAutoConfiguration.java, blossom-autoconfigure/src/main/java/com/blossomproject/autoconfigure/ui/WebSecurityAutoConfiguration.java
Make the autoconfiguration fail less often when some dependencies are not present:
- Allow web applications to not depend on blossom-ui-common
- Do not create / depend on an Elasticsearch Client when Elasticsearch is not present
=> Autoconfiguration improvements

.travis.yml
Oracle JDK 8 has been out of support for a while, and it seems Travis removed support for it.
This PR switches the build to use OpenJDK 8
=> Build with OpenJDK 8

blossom-core/blossom-core-common/src/main/java/com/blossomproject/core/common/dao/GenericReadOnlyDaoImpl.java
Making the constructor of GenricReadOnlyDaoImpl public as it makes no senss for it to be package protected as its purpose is to be inherited
=> Fix for issue 233
